web:
  build: .
  ports:
    - "5000:80"
  volumes:
    - ./code:/var/www/html
  links:
    - redis
    - mysql
redis:
  image: redis
mysql:
  image: mysql:5.6
  env_file: mysql.env
  ports:
   - "3306:3306"
